web/router.ex
defmodule ProjectX.Router do
  use ProjectX.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ProjectX do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/hello", HelloController, :index
    get "/register", RegistrationController, :new
    post "/register", RegistrationController, :create


# login画面表示
# login処理
# logout処理

    get "/login", SessionController, :new
    post "/login", SessionController, :create
    delete "/logout", SessionController, :delete
  end

  # Other scopes may use custom stacks.
  # scope "/api", ProjectX do
  #   pipe_through :api
  # end
end

lib/projectX/endpoint.ex
defmodule ProjectX.Endpoint do
  use Phoenix.Endpoint, otp_app: :projectX

  socket "/socket", ProjectX.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :projectX, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_projectX_key",
    signing_salt: "1ZvMcIMt"

  plug ProjectX.Router
end

lib/projectX/repo.ex
defmodule ProjectX.Repo do
  use Ecto.Repo, otp_app: :projectX
end

web/models/session.ex
defmodule ProjectX.Session do
    alias ProjectX.User


    @doc """
    ログイン処理をする

    get_by関数でUserモデルをemailで取得します
    authenticateが成功すれば、{:ok, user}を返し、失敗すれば:errorを返します
    """
    def login(params, repo) do
        user = repo.get_by(User, email: String.downcase(params["email"]))
        case authenticate(user, params["password"]) do
          true -> {:ok, user}
          _    -> :error
        end
    end

    @doc """
    認証処理をする

    Comeonin.Bcrypt.checkpw関数でpasswordをハッシュ化してデータベースのハッシュ値と比較します
    """
    defp authenticate(user, password) do
        case user do
          nil -> false
          _   -> Comeonin.Bcrypt.checkpw(password, user.crypted_password)
        end
    end

    @doc """
    現在のログインユーザを取得するヘルパー関数

    get_session関数で:current_userからidを取得し、idが存在する場合はDBからUser情報を取得します
    """
    def current_user(conn) do
        id = Plug.Conn.get_session(conn, :current_user)
        if id, do: ProjectX.Repo.get(User, id)
    end


    @doc """
    ログインしているかどうかを返すヘルパー関数
    """
    def logged_in?(conn) do
       !!current_user(conn)
    end
end

web/models/user.ex
defmodule ProjectX.User do
  use ProjectX.Web, :model

  schema "users" do
    field :email, :string
    field :crypted_password, :string
    # passwordフィールドを追加。virtual: trueとすることでデータベースには保存されない
    field :password, :string, virtual: true

    timestamps
  end

  # crypted_passwordの代わりにpasswordに変更
  # @required_fields ~w(email crypted_password)
  @required_fields ~w(email password)
  @optional_fields ~w()

  @doc """
  "model"と"params"に基づいたchangesetを作成する
  "params"がない場合は、invalidなchangesetを返します。

  castはparamsの値でモデルの値を設定
  update_changeは、"email"の値をフィールドの値を小文字に変更
  unique_constraintは、"email"にユニーク制約のバリデーション
  validate_formatは、"email"に"@"が含まれているかバリデーション
  validate_lengthは、"password"が5文字以上であるかバリデーション
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
    |> update_change(:email, &String.downcase/1)
    |> unique_constraint(:email)
    |> validate_format(:email, ~r/@/)
    |> validate_length(:password, min: 5)
  end

    @doc """
  userレコードを1件作成する

  put_changeは、crypated_passwordに値を設定
  insert()は、テーブルにレコードを作成(SQLのinsert文が走る)
  ectoの関数であり、より詳細を知りたい場合は、http://www.phoenixframework.org/docs/ecto-models を参照してください
  """
  def create(changeset, repo) do
    changeset
    |> put_change(:crypted_password, hashed_password(changeset.params["password"]))
    |> repo.insert()
  end

  @doc """
  パスワードをハッシュ値にする
  Comeoninという値をハッシュ化するライブラリを使用しています
  defpはプライベートメソッド
  """
  defp hashed_password(password) do
    Comeonin.Bcrypt.hashpwsalt(password)
  end
end

web/controllers/hello_controller.ex
defmodule ProjectX.HelloController do
    use ProjectX.Web, :controller

    # indexアクション
    #  conn - リクエスト情報を保持
    #  params - クエリストリングやフォーム入力などのパラメータ
    def index(conn, _params) do
        # index.html.eexテンプレートを表示する
        render conn, "index.html"
    end
end

web/controllers/page_controller.ex
defmodule ProjectX.PageController do
  use ProjectX.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

web/controllers/registration_controller.ex
defmodule ProjectX.RegistrationController do
  use ProjectX.Web, :controller
  alias ProjectX.User

  @doc """
  ユーザ登録画面の表示
  """
  def new(conn, _params) do
    # chnageset関数は、newメソッドのようなもので、Userのデータを返す
    changeset = User.changeset(%User{})
    # renderの第三引数に値を渡すことで、ビューやテンプレートで値を使用できる
    render conn, "new.html", changeset: changeset
  end



  def create(conn, %{"user" => user_params}) do
    # フォーム情報user_paramsの値でuserデータを作成
    changeset = User.changeset(%User{}, user_params)

    # ユーザ登録
    case User.create(changeset, ProjectX.Repo) do
      {:ok, user} ->
        # バリデーションに成功した場合、userレコードを作成し、ログインし、"/"にリダイレクト
        conn
        |> put_session(:current_user, user.id)
        |> put_flash(:info, "ようこそ" <> changeset.params["email"])
        |> redirect(to: "/")
      {:error, changeset} ->
        # バリデーションに失敗した場合、"new.html"を表示
        conn
        |> put_flash(:info, "アカウントを作成できませんでした")
        |> render("new.html", changeset: changeset)
    end
  end
end

web/controllers/session_controller.ex
defmodule ProjectX.SessionController do
    use ProjectX.Web, :controller
    alias ProjectX.User

    @doc """
    ログイン画面の表示
    """
    def new(conn, _params) do
        render conn, "new.html"
    end


    def create(conn, %{"session" => session_params}) do
    # Sessionモジュールのlogin関数でログイン可否を判定する
        case ProjectX.Session.login(session_params, ProjectX.Repo) do
          # ログイン成功の場合、セッションにuser.idを設定し、ホーム("/")にリダイレクトする
          {:ok, user} ->
            conn
            |> put_session(:current_user, user.id)
            |> put_flash(:info, "ログインしました")
            |> redirect(to: "/")
          # errorの場合、ログイン画面を再表示する
          :error ->
            conn
            |> put_flash(:info, "メールアドレスかパスワードが間違っています")
            |> render("new.html")
        end
    end


    @doc """
    ログアウト処理

    delete_sessionでセッション情報を削除し、ホーム("/")にリダイレクトする
    """
    def delete(conn, _) do
        conn
        |> delete_session(:current_user)
        |> put_flash(:info, "ログアウトしました")
        |> redirect(to: "/")
    end
end

web/views/error_view.ex
defmodule ProjectX.ErrorView do
  use ProjectX.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/hello_view.ex
defmodule ProjectX.HelloView do
  # Webのviewモジュールを使用できるようにする(おまじないのようなもの)
  use ProjectX.Web, :view
end

web/views/layout_view.ex
defmodule ProjectX.LayoutView do
  use ProjectX.Web, :view
end

web/views/page_view.ex
defmodule ProjectX.PageView do
  use ProjectX.Web, :view
end

web/views/registration_view.ex
defmodule ProjectX.RegistrationView do
  use ProjectX.Web, :view
end

web/views/session_view.ex
defmodule ProjectX.SessionView do
    use ProjectX.Web, :view
end

web/templates/hello/index.html.eex
<div class="jumbotron">
  <h2>Hello Phoenix!!</h2>
</div>

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello ProjectX!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <ul class="nav nav-pills pull-right">
          <%= if logged_in?(@conn) do %>
            <li><%= current_user(@conn).email %></li>
            <li><%= link "ログアウト", to: session_path(@conn, :delete), method: :delete %></li>
          <% else %>
            <li><%= link "ユーザ登録", to: registration_path(@conn, :new) %></li>
            <li><%= link "ログイン", to: session_path(@conn, :new) %></li>
          <% end %>
        </ul>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}", name: "Phoenix!" %></h2>
  <p class="lead">A productive web framework that<br />does not compromise speed and maintainability.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="https://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>

web/templates/session/new.html.eex
<h1>ログイン</h1>

<%= form_for @conn, session_path(@conn, :create), [name: :session], fn form -> %>
  <div class="form-group">
    <label>メールアドレス</label>
    <%= email_input form, :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <label>パスワード</label>
    <%= password_input form, :password, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= submit "ログイン", class: "btn btn-primary" %>
  </div>
<% end %>